insert into Products(Name,Description,Price,ImageName) values('Arepa con chorizo','Deliciosa arepa acompañada de chorizo de su res o pollo',2500,'https://raw.githubusercontent.com/Jucer74/WebDevelopment/main/Proyecto/ImageProducts/Arepa-Con-Chorizo.jpg ');
insert into Products(Name,Description,Price,ImageName) values('Arepa con carne','Deliciosa arepa acompañada con carne de res',2500,'https://raw.githubusercontent.com/Jucer74/WebDevelopment/main/Proyecto/ImageProducts/Arepa-Rellena-Carne.jpg ');
insert into Products(Name,Description,Price,ImageName) values('Arepa con todo','Deliciosa arepa acompañada con carne, pollo, chocharrón, huevo y salsas de la casa',7000,'https://raw.githubusercontent.com/Jucer74/WebDevelopment/main/Proyecto/ImageProducts/Arepa-Rellena-Con-Todo.jpg ');
insert into Products(Name,Description,Price,ImageName) values('Arepa con queso cuajada','Deliciosa arepa acompañada con un queso cuajada',3000,'https://raw.githubusercontent.com/Jucer74/WebDevelopment/main/Proyecto/ImageProducts/Arepa-Rellena-de-Queso-Cuajada.jpg ');
insert into Products(Name,Description,Price,ImageName) values('Arepa con queso ','Deliciosa arepa rellena con un queso tajado',3000,'https://raw.githubusercontent.com/Jucer74/WebDevelopment/main/Proyecto/ImageProducts/Arepa-Rellena-de-Queso.jpg ');
insert into Products(Name,Description,Price,ImageName) values('Arepa con huevos revueltos ','Deliciosa arepa rellena de huevos revueltos',2500,'https://raw.githubusercontent.com/Jucer74/WebDevelopment/main/Proyecto/ImageProducts/Arepa-Rellena-Huevos-Revueltos.jpg ');
insert into Products(Name,Description,Price,ImageName) values('Arepa con jamon y queso','Deliciosa arepa rellena con jamón y queso',2500,'https://raw.githubusercontent.com/Jucer74/WebDevelopment/main/Proyecto/ImageProducts/Arepa-Rellena-Jamon-Queso.jpg ');
insert into Products(Name,Description,Price,ImageName) values('Arepa con pollo','Deliciosa arepa rellena con pollo',3500,'https://raw.githubusercontent.com/Jucer74/WebDevelopment/main/Proyecto/ImageProducts/Arepa-Rellena-Pollo.jpg ');
insert into Products(Name,Description,Price,ImageName) values('Arepa con salchicha ','Deliciosa arepa rellena de salchicha ranchera',3000,'https://raw.githubusercontent.com/Jucer74/WebDevelopment/main/Proyecto/ImageProducts/Arepa-Rellena-Salchicha-Ranchera.png ');
insert into Products(Name,Description,Price,ImageName) values('Arepa sencilla','Deliciosa arepa sencilla',700,'https://raw.githubusercontent.com/Jucer74/WebDevelopment/main/Proyecto/ImageProducts/Arepa-Sencilla.jpg ');

select * from Products